EducationCertificate.find_or_create_by(name: "10th MARK SHEET", short_name: "X")
EducationCertificate.find_or_create_by(name: "12th MARK SHEET", short_name: "XII")
EducationCertificate.find_or_create_by(name: "UG MARK SHEET", short_name: "UGM")
EducationCertificate.find_or_create_by(name: "PG MARK SHEET", short_name: "PGM")
EducationCertificate.find_or_create_by(name: "UG PROVISIONAL", short_name: "UGP")
EducationCertificate.find_or_create_by(name: "PG PROVISIONAL", short_name: "PGP")
EducationCertificate.find_or_create_by(name: "UG DEGREE", short_name: "UGD")
EducationCertificate.find_or_create_by(name: "PG DEGREE", short_name: "PGD")
EducationCertificate.find_or_create_by(name: "DIPLOMA MARKSHEET", short_name: "DIP")
EducationCertificate.find_or_create_by(name: "DIPLOMA PROVISIONAL", short_name: "DIPP")
EducationCertificate.find_or_create_by(name: "DIPLOMA DEGREE", short_name: "DIPM")


EmploymentCertificate.find_or_create_by(name: "JOINING LETTER", short_name: "JOINLTR")
EmploymentCertificate.find_or_create_by(name: "APPARISAL LETTER", short_name: "APPLTR")
EmploymentCertificate.find_or_create_by(name: "RELIEVING LETTER", short_name: "RELLTR")
EmploymentCertificate.find_or_create_by(name: "EXPERIENCE LETTER", short_name: "EXPLTR")

EmployeeAgreementType.find_or_create_by(name: "BOND LETTER", short_name: "BDLTR")
EmployeeAgreementType.find_or_create_by(name: "JOINING LETTER", short_name: "JOILTR")
EmployeeAgreementType.find_or_create_by(name: "APPARISAL LETTER", short_name: "APPLTR")
EmployeeAgreementType.find_or_create_by(name: "RELIEVING LETTER", short_name: "RELLTR")
EmployeeAgreementType.find_or_create_by(name: "PROMOTION LETTER", short_name: "PROLTR")
EmployeeAgreementType.find_or_create_by(name: "EXPERIENCE LETTER", short_name: "EXPLTR")
EmployeeAgreementType.find_or_create_by(name: "RESIGNATION ACCEPTANCE LETTER", short_name: "RESLTR")
