Role.find_or_create_by(name: "PORTAL ADMIN", short_name: "PA", grade: "XX")
Role.find_or_create_by(name: "ADMIN", short_name: "AD", grade: "X")
Role.find_or_create_by(name: "MANAGER", short_name: "M", grade: "A")
Role.find_or_create_by(name: "TEAM LEAD", short_name: "TL", grade: "B")
Role.find_or_create_by(name: "SENIOR SOFTWARE ENGINEER", short_name: "SSE", grade: "C")
Role.find_or_create_by(name: "SOFTWARE ENGINEER", short_name: "SE", grade: "D")
Role.find_or_create_by(name: "SOFTWARE ENGINEER TRAINEE", short_name: "SET", grade: "E")