YearlyHolidayCalendar.find_or_create_by(holiday_date: "14/01/2017", description: "Pongal")
YearlyHolidayCalendar.find_or_create_by(holiday_date: "26/01/2017", description: "Republic Day")
YearlyHolidayCalendar.find_or_create_by(holiday_date: "14/04/2017", description: "Tamil New Year")
YearlyHolidayCalendar.find_or_create_by(holiday_date: "01/05/2017", description: "May Day")
YearlyHolidayCalendar.find_or_create_by(holiday_date: "26/06/2017", description: "Ramazan")
YearlyHolidayCalendar.find_or_create_by(holiday_date: "15/08/2017", description: "Independence Day")
YearlyHolidayCalendar.find_or_create_by(holiday_date: "25/08/2017", description: "Ganesh Chaturthi")
YearlyHolidayCalendar.find_or_create_by(holiday_date: "02/10/2017", description: "Gandhi Jayanthi")
YearlyHolidayCalendar.find_or_create_by(holiday_date: "18/10/2017", description: "Diwali")
YearlyHolidayCalendar.find_or_create_by(holiday_date: "25/12/2017", description: "Christmas")